server:
  port: 8084

spring:
  application:
    name: order  

  datasource:
    url: jdbc:postgresql://${HOST_DB_POSTGRE_USER_ECOMMERCE}:${PORT_DB_POSTGRE_USER_ECOMMERCE}/ecommerce_db  
    username: ${USER_DB_POSTGRE}
    password: ${PASS_DB_POSTGRE}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update  # ⚠️ Cambiar a "validate" en producción
    show-sql: true 
    properties:
      hibernate:
        format_sql: true  # Formatea las consultas SQL para mayor legibilidad

  cloud:
    discovery:
      enabled: true
    eureka:
      client:
        serviceUrl:
          defaultZone: "http://${USER_EUREKA}:${PASS_EUREKA}@${HOST_EUREKA}:${PORT_EUREKA}/eureka/"
        registerWithEureka: true
        fetchRegistry: true
        eurekaServerBasicAuthUserName: ${USER_EUREKA}
        eurekaServerBasicAuthUserPassword: ${PASS_EUREKA}
      instance:
        hostname: ${HOST_EUREKA}
        preferIpAddress: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${HOST_KEYCLOAK}:${PORT_KEYCLOAK}/realms/UsersRealm

  management:
    endpoints:
      web:
        exposure:
          include: "*"
      endpoint:
        health:
          show-details: always

kafka:
  bootstrap-servers: ${HOST_KAFKA}:${PORT_KAFKA}
  consumer:
    group-id: order_group
    auto-offset-reset: earliest
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  producer:
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: org.apache.kafka.common.serialization.StringSerializer
  topic:
    order-events: order-events

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    operationsSorter: alpha
    tagsSorter: alpha
  override-with-gateway-url: false  # 🔥 redirige Swagger a través del API Gateway

# Permitir acceso público a Swagger en Security
security:
  ignored:
    - /v3/api-docs
    - /swagger-ui.html
    - /swagger-ui/**
    - /webjars/**

logging:
  level:
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
