server:
  port: 8083  

spring:
  application:
    name: authentication

  data:
    mongodb:
      uri: mongodb://localhost:27017/user_ecommerce  

  cloud:
    discovery:
      enabled: true
    eureka:
      client:
        serviceUrl:
          defaultZone: http://admin:admin@localhost:8761/eureka/
        registerWithEureka: true
        fetchRegistry: true
        server:
          username: admin
          password: admin
      instance:
        hostname: localhost
        preferIpAddress: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/UsersRealm

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: authentication_group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

keycloak:
  auth:
    realm: UsersRealm
    server-url: http://localhost:8080
    client-id: login
    client-secret: pbdtQ4qdlqrLlPEhO6tNNe6JIbeI2Kvh

# ✅ Configuración de SpringDoc OpenAPI para exponer la documentación en Swagger
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    operationsSorter: alpha
    tagsSorter: alpha
  override-with-gateway-url: true  # 🔥 No redirige Swagger a través del API Gateway

# Permitir acceso público a Swagger en Security
security:
  ignored:
    - /v3/api-docs
    - /swagger-ui.html
    - /swagger-ui/**
    - /webjars/**

logging:
  level:
    org.springframework: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
